### ISSUE TITLE
channel trait error

### ISSUE THREAD

**Issue by jpoeppelman1** [mikejac/node-red-contrib-google-smarthome#183]
Using the tv device and channel trait, it fails..  Here is the log file and my channel.json config file.

{
  "availableChannels": [
    {
      "key": "ktvu2",
      "names": [
        "Fox",
        "KTVU"
      ],
      "number": "2"
    },
    {
      "key": "abc1",
      "names": [
        "ABC",
        "ABC East"
      ],
      "number": "4-11"
    }
  ]
}

=================================================

HttpActions:httpActionsRegister(/smarthome): reqdata = {"inputs":[{"context":{"locale_country":"US","locale_language":"en"},"intent":"action.devices.EXECUTE","payload":{"commands":[{"devices":[{"id":"113eab45.a34b85"}],"execution":[{"command":"action.devices.commands.selectChannel","params":{"channelNumber":"4"}}]}]}}],"requestId":"8703446303919430367"}
HttpActions:httpActionsRegister(/smarthome): user: test
HttpActions:httpActionsRegister(/smarthome): EXECUTE
HttpActions:_exec()
HttpActions:_execDevice(): command = {"command":"action.devices.commands.selectChannel","params":{"channelNumber":"4"}}
Device:execCommand(): device = {"id":"113eab45.a34b85","states":{},"command":"action.devices.commands.selectChannel"}
TypeError: this.available_channels.forEach is not a function
    at MediaNode.execCommand (/data/node_modules/node-red-contrib-google-smarthome/devices/media.js:1015:45)
    at GoogleSmartHome.execCommand (/data/node_modules/node-red-contrib-google-smarthome/lib/Devices.js:159:49)
    at GoogleSmartHome._execDevice (/data/node_modules/node-red-contrib-google-smarthome/lib/HttpActions.js:389:27)
    at GoogleSmartHome._exec (/data/node_modules/node-red-contrib-google-smarthome/lib/HttpActions.js:335:50)
    at /data/node_modules/node-red-contrib-google-smarthome/lib/HttpActions.js:209:28
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:281:22

**Comment by ckhmer1** [comment]
The channel JSON is wrong, if I remember well it should be only the array (the actual value of he availableChannels JSON.

**Comment by jpoeppelman1** [comment]
Okay, I took the example from google documentation.   Do you have working example?

**Comment by ckhmer1** [comment]
Hi,
try to import the test flow from [here](https://raw.githubusercontent.com/mikejac/node-red-contrib-google-smarthome/master/test/sh/flows.json)

**Comment by jpoeppelman1** [comment]
This worked, thank you!
