### ISSUE TITLE
v0.2.7 - node-RED stopped

### ISSUE THREAD

**Issue by Paul-Reed** [mikejac/node-red-contrib-google-smarthome#251]
I've just updated from v0.2.6 to v0.2.7 and upon restarting node-RED failed to load (endless loop).
```
1 Feb 11:02:02 - [red] Uncaught Exception:
1 Feb 11:02:02 - [error] TypeError: Cannot read property 'persistent_state' of null
    at /home/pi/.node-red/node_modules/node-red-contrib-google-smarthome/lib/Devices.js:286:40
    at Array.forEach (<anonymous>)
    at GoogleSmartHome.getStates (/home/pi/.node-red/node_modules/node-red-contrib-google-smarthome/lib/Devices.js:280:38)
    at MgmtNode.sendSetState (/home/pi/.node-red/node_modules/node-red-contrib-google-smarthome/google-smarthome.js:330:46)
    at /home/pi/.node-red/node_modules/node-red-contrib-google-smarthome/lib/SmartHome.js:487:96
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (/home/pi/.node-red/node_modules/node-red-contrib-google-smarthome/lib/SmartHome.js:487:53)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
```
I haven't time to investigate further at the moment, so I've rolled back to v0.2.6 which is working OK

**Comment by ckhmer1** [comment]
Cout You please try my PR #249 ?

**Comment by Paul-Reed** [comment]
@ckhmer1 https://github.com/mikejac/node-red-contrib-google-smarthome/pull/249 indeed fixes the problem
